function iutilities_filter($op, $delta = 0, $format = -1, $text = '') {
  switch ($op) {
    case 'list':
      return array(
        0 => t('Wrap body field content')
      );

    case 'description':
      return t('Wraps the content of the body field for easier styling when other fields get included in the content');

    case 'settings':
      // no settings for this filter
      break;

    case 'no cache':
      //it's ok to cache this filter's output
      return FALSE;

    case 'prepare':
      //no preparations to make
      return $text;

    case 'process':
      return '<div class="body-field-content">' . $text . '</div>';

    default:
      return $text;
  }
}

